### ISSUE TITLE
Great work! Also recommending RL4CO library

### ISSUE THREAD

**Issue by henry-yeh** [EMI-Group/tensoraco#1]
Great work! We also implemented tensorized versions of ACO in [RL4CO](https://github.com/ai4co/rl4co) and [DeepACO](https://github.com/henry-yeh/DeepACO), and they are not limited to TSP. 

Welcome to take a look! We look forward to further discussions and potential integration of our codebases.

**Comment by JiangTao97** [comment]
Thank you for sharing your work on implementing tensorized versions of ACO in RL4CO and DeepACO, and for your interest in our projects. We appreciate the significant efforts and insights your projects bring to the field. We look forward to discussing potential integrations between our codebases.
